# Generated by Django 5.0.6 on 2024-09-09 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IOT', '0002_device_device_token_alter_device_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_token',
        ),
    ]
