# Generated by Django 5.0.6 on 2024-09-09 16:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOT', '0003_remove_device_device_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
