# Generated by Django 5.0.6 on 2024-09-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOT', '0004_device_device_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Device-Images'),
        ),
    ]
